# Generated by Django 4.2.13 on 2024-09-27 22:02

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='portfolio/', validators=[home.models.validate_image_extension])),
                ('link', models.URLField()),
            ],
        ),
    ]
